// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/mafia_grpc/mafia_grpc.proto

package mafia_grpc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NotificationType int32

const (
	NotificationType_START     NotificationType = 0
	NotificationType_FINISH    NotificationType = 1
	NotificationType_NEW_DAY   NotificationType = 2
	NotificationType_NEW_NIGHT NotificationType = 3
)

var NotificationType_name = map[int32]string{
	0: "START",
	1: "FINISH",
	2: "NEW_DAY",
	3: "NEW_NIGHT",
}

var NotificationType_value = map[string]int32{
	"START":     0,
	"FINISH":    1,
	"NEW_DAY":   2,
	"NEW_NIGHT": 3,
}

func (x NotificationType) String() string {
	return proto.EnumName(NotificationType_name, int32(x))
}

func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fa11038ec5e9ab77, []int{0}
}

type Response struct {
	Ok                   bool     `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa11038ec5e9ab77, []int{0}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetOk() bool {
	if m != nil {
		return m.Ok
	}
	return false
}

type CheckMafiaResponse struct {
	IsMafia              bool     `protobuf:"varint,1,opt,name=isMafia,proto3" json:"isMafia,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckMafiaResponse) Reset()         { *m = CheckMafiaResponse{} }
func (m *CheckMafiaResponse) String() string { return proto.CompactTextString(m) }
func (*CheckMafiaResponse) ProtoMessage()    {}
func (*CheckMafiaResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa11038ec5e9ab77, []int{1}
}

func (m *CheckMafiaResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckMafiaResponse.Unmarshal(m, b)
}
func (m *CheckMafiaResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckMafiaResponse.Marshal(b, m, deterministic)
}
func (m *CheckMafiaResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckMafiaResponse.Merge(m, src)
}
func (m *CheckMafiaResponse) XXX_Size() int {
	return xxx_messageInfo_CheckMafiaResponse.Size(m)
}
func (m *CheckMafiaResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckMafiaResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckMafiaResponse proto.InternalMessageInfo

func (m *CheckMafiaResponse) GetIsMafia() bool {
	if m != nil {
		return m.IsMafia
	}
	return false
}

type ChatResponse struct {
	CanChat              bool     `protobuf:"varint,1,opt,name=canChat,proto3" json:"canChat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChatResponse) Reset()         { *m = ChatResponse{} }
func (m *ChatResponse) String() string { return proto.CompactTextString(m) }
func (*ChatResponse) ProtoMessage()    {}
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa11038ec5e9ab77, []int{2}
}

func (m *ChatResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChatResponse.Unmarshal(m, b)
}
func (m *ChatResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChatResponse.Marshal(b, m, deterministic)
}
func (m *ChatResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChatResponse.Merge(m, src)
}
func (m *ChatResponse) XXX_Size() int {
	return xxx_messageInfo_ChatResponse.Size(m)
}
func (m *ChatResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChatResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChatResponse proto.InternalMessageInfo

func (m *ChatResponse) GetCanChat() bool {
	if m != nil {
		return m.CanChat
	}
	return false
}

type PlayerInfo struct {
	Session              string   `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerInfo) Reset()         { *m = PlayerInfo{} }
func (m *PlayerInfo) String() string { return proto.CompactTextString(m) }
func (*PlayerInfo) ProtoMessage()    {}
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa11038ec5e9ab77, []int{3}
}

func (m *PlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerInfo.Unmarshal(m, b)
}
func (m *PlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerInfo.Marshal(b, m, deterministic)
}
func (m *PlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerInfo.Merge(m, src)
}
func (m *PlayerInfo) XXX_Size() int {
	return xxx_messageInfo_PlayerInfo.Size(m)
}
func (m *PlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerInfo proto.InternalMessageInfo

func (m *PlayerInfo) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *PlayerInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type JoinRequest struct {
	Player               *PlayerInfo `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *JoinRequest) Reset()         { *m = JoinRequest{} }
func (m *JoinRequest) String() string { return proto.CompactTextString(m) }
func (*JoinRequest) ProtoMessage()    {}
func (*JoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa11038ec5e9ab77, []int{4}
}

func (m *JoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JoinRequest.Unmarshal(m, b)
}
func (m *JoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JoinRequest.Marshal(b, m, deterministic)
}
func (m *JoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JoinRequest.Merge(m, src)
}
func (m *JoinRequest) XXX_Size() int {
	return xxx_messageInfo_JoinRequest.Size(m)
}
func (m *JoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_JoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_JoinRequest proto.InternalMessageInfo

func (m *JoinRequest) GetPlayer() *PlayerInfo {
	if m != nil {
		return m.Player
	}
	return nil
}

type SetVictimRequest struct {
	Player               *PlayerInfo `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	Victim               string      `protobuf:"bytes,2,opt,name=victim,proto3" json:"victim,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SetVictimRequest) Reset()         { *m = SetVictimRequest{} }
func (m *SetVictimRequest) String() string { return proto.CompactTextString(m) }
func (*SetVictimRequest) ProtoMessage()    {}
func (*SetVictimRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa11038ec5e9ab77, []int{5}
}

func (m *SetVictimRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetVictimRequest.Unmarshal(m, b)
}
func (m *SetVictimRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetVictimRequest.Marshal(b, m, deterministic)
}
func (m *SetVictimRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetVictimRequest.Merge(m, src)
}
func (m *SetVictimRequest) XXX_Size() int {
	return xxx_messageInfo_SetVictimRequest.Size(m)
}
func (m *SetVictimRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetVictimRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetVictimRequest proto.InternalMessageInfo

func (m *SetVictimRequest) GetPlayer() *PlayerInfo {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *SetVictimRequest) GetVictim() string {
	if m != nil {
		return m.Victim
	}
	return ""
}

type GameState struct {
	Session              string   `protobuf:"bytes,1,opt,name=session,proto3" json:"session,omitempty"`
	AlivePlayers         []string `protobuf:"bytes,2,rep,name=alivePlayers,proto3" json:"alivePlayers,omitempty"`
	Date                 int32    `protobuf:"varint,3,opt,name=date,proto3" json:"date,omitempty"`
	IsDay                bool     `protobuf:"varint,4,opt,name=isDay,proto3" json:"isDay,omitempty"`
	IsStarted            bool     `protobuf:"varint,5,opt,name=isStarted,proto3" json:"isStarted,omitempty"`
	IsFinished           bool     `protobuf:"varint,6,opt,name=isFinished,proto3" json:"isFinished,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameState) Reset()         { *m = GameState{} }
func (m *GameState) String() string { return proto.CompactTextString(m) }
func (*GameState) ProtoMessage()    {}
func (*GameState) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa11038ec5e9ab77, []int{6}
}

func (m *GameState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameState.Unmarshal(m, b)
}
func (m *GameState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameState.Marshal(b, m, deterministic)
}
func (m *GameState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameState.Merge(m, src)
}
func (m *GameState) XXX_Size() int {
	return xxx_messageInfo_GameState.Size(m)
}
func (m *GameState) XXX_DiscardUnknown() {
	xxx_messageInfo_GameState.DiscardUnknown(m)
}

var xxx_messageInfo_GameState proto.InternalMessageInfo

func (m *GameState) GetSession() string {
	if m != nil {
		return m.Session
	}
	return ""
}

func (m *GameState) GetAlivePlayers() []string {
	if m != nil {
		return m.AlivePlayers
	}
	return nil
}

func (m *GameState) GetDate() int32 {
	if m != nil {
		return m.Date
	}
	return 0
}

func (m *GameState) GetIsDay() bool {
	if m != nil {
		return m.IsDay
	}
	return false
}

func (m *GameState) GetIsStarted() bool {
	if m != nil {
		return m.IsStarted
	}
	return false
}

func (m *GameState) GetIsFinished() bool {
	if m != nil {
		return m.IsFinished
	}
	return false
}

type Notification struct {
	Type      NotificationType `protobuf:"varint,1,opt,name=type,proto3,enum=mafia_grpc.NotificationType" json:"type,omitempty"`
	GameState *GameState       `protobuf:"bytes,2,opt,name=gameState,proto3" json:"gameState,omitempty"`
	// Types that are valid to be assigned to Details:
	//	*Notification_Role
	//	*Notification_KilledPlayer
	//	*Notification_Mafia
	Details              isNotification_Details `protobuf_oneof:"details"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *Notification) Reset()         { *m = Notification{} }
func (m *Notification) String() string { return proto.CompactTextString(m) }
func (*Notification) ProtoMessage()    {}
func (*Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa11038ec5e9ab77, []int{7}
}

func (m *Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Notification.Unmarshal(m, b)
}
func (m *Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Notification.Marshal(b, m, deterministic)
}
func (m *Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Notification.Merge(m, src)
}
func (m *Notification) XXX_Size() int {
	return xxx_messageInfo_Notification.Size(m)
}
func (m *Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_Notification proto.InternalMessageInfo

func (m *Notification) GetType() NotificationType {
	if m != nil {
		return m.Type
	}
	return NotificationType_START
}

func (m *Notification) GetGameState() *GameState {
	if m != nil {
		return m.GameState
	}
	return nil
}

type isNotification_Details interface {
	isNotification_Details()
}

type Notification_Role struct {
	Role string `protobuf:"bytes,3,opt,name=role,proto3,oneof"`
}

type Notification_KilledPlayer struct {
	KilledPlayer string `protobuf:"bytes,4,opt,name=killedPlayer,proto3,oneof"`
}

type Notification_Mafia struct {
	Mafia string `protobuf:"bytes,5,opt,name=mafia,proto3,oneof"`
}

func (*Notification_Role) isNotification_Details() {}

func (*Notification_KilledPlayer) isNotification_Details() {}

func (*Notification_Mafia) isNotification_Details() {}

func (m *Notification) GetDetails() isNotification_Details {
	if m != nil {
		return m.Details
	}
	return nil
}

func (m *Notification) GetRole() string {
	if x, ok := m.GetDetails().(*Notification_Role); ok {
		return x.Role
	}
	return ""
}

func (m *Notification) GetKilledPlayer() string {
	if x, ok := m.GetDetails().(*Notification_KilledPlayer); ok {
		return x.KilledPlayer
	}
	return ""
}

func (m *Notification) GetMafia() string {
	if x, ok := m.GetDetails().(*Notification_Mafia); ok {
		return x.Mafia
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Notification) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Notification_Role)(nil),
		(*Notification_KilledPlayer)(nil),
		(*Notification_Mafia)(nil),
	}
}

func init() {
	proto.RegisterEnum("mafia_grpc.NotificationType", NotificationType_name, NotificationType_value)
	proto.RegisterType((*Response)(nil), "mafia_grpc.Response")
	proto.RegisterType((*CheckMafiaResponse)(nil), "mafia_grpc.CheckMafiaResponse")
	proto.RegisterType((*ChatResponse)(nil), "mafia_grpc.ChatResponse")
	proto.RegisterType((*PlayerInfo)(nil), "mafia_grpc.PlayerInfo")
	proto.RegisterType((*JoinRequest)(nil), "mafia_grpc.JoinRequest")
	proto.RegisterType((*SetVictimRequest)(nil), "mafia_grpc.SetVictimRequest")
	proto.RegisterType((*GameState)(nil), "mafia_grpc.GameState")
	proto.RegisterType((*Notification)(nil), "mafia_grpc.Notification")
}

func init() {
	proto.RegisterFile("pkg/mafia_grpc/mafia_grpc.proto", fileDescriptor_fa11038ec5e9ab77)
}

var fileDescriptor_fa11038ec5e9ab77 = []byte{
	// 607 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0xdd, 0x6e, 0xd3, 0x4c,
	0x10, 0xb5, 0x53, 0x3b, 0xa9, 0x27, 0xf9, 0x2a, 0x6b, 0xd4, 0xaf, 0x58, 0x51, 0x55, 0xaa, 0x15,
	0x17, 0x11, 0x17, 0x69, 0x95, 0x4a, 0x20, 0x01, 0xbd, 0xe8, 0x6f, 0x12, 0x10, 0x11, 0x38, 0x51,
	0x11, 0xbd, 0xa9, 0x16, 0x67, 0xd3, 0xae, 0xec, 0x78, 0x4d, 0x76, 0x5b, 0x29, 0xaf, 0xc0, 0xdb,
	0xf0, 0x2e, 0x3c, 0x10, 0xf2, 0x3a, 0x69, 0x36, 0x85, 0x54, 0xa8, 0x77, 0x3b, 0x67, 0xce, 0xcc,
	0xce, 0x99, 0x9d, 0x59, 0x78, 0x9e, 0xc5, 0xd7, 0x7b, 0x63, 0x3a, 0xe2, 0xf4, 0xea, 0x7a, 0x92,
	0x45, 0xc6, 0xb1, 0x99, 0x4d, 0x84, 0x12, 0x08, 0x0b, 0x84, 0xd4, 0x61, 0x3d, 0x64, 0x32, 0x13,
	0xa9, 0x64, 0xb8, 0x01, 0x25, 0x11, 0x07, 0xf6, 0xae, 0xdd, 0x58, 0x0f, 0x4b, 0x22, 0x26, 0x4d,
	0xc0, 0x93, 0x1b, 0x16, 0xc5, 0x1f, 0x73, 0xfa, 0x3d, 0x2b, 0x80, 0x0a, 0x97, 0x1a, 0x9a, 0x51,
	0xe7, 0x26, 0x69, 0x40, 0xed, 0xe4, 0x86, 0x2a, 0x93, 0x19, 0xd1, 0x34, 0x87, 0xe6, 0xcc, 0x99,
	0x49, 0xde, 0x00, 0x7c, 0x4a, 0xe8, 0x94, 0x4d, 0xba, 0xe9, 0x48, 0xe4, 0x3c, 0xc9, 0xa4, 0xe4,
	0x22, 0xd5, 0x3c, 0x2f, 0x9c, 0x9b, 0x88, 0xe0, 0xa4, 0x74, 0xcc, 0x82, 0x92, 0x86, 0xf5, 0x99,
	0x1c, 0x42, 0xf5, 0xbd, 0xe0, 0x69, 0xc8, 0xbe, 0xdf, 0x32, 0xa9, 0xb0, 0x09, 0xe5, 0x4c, 0xa7,
	0xd2, 0xb1, 0xd5, 0xd6, 0x56, 0xd3, 0xd0, 0xbb, 0xb8, 0x24, 0x9c, 0xb1, 0xc8, 0x25, 0xf8, 0x7d,
	0xa6, 0x2e, 0x78, 0xa4, 0xf8, 0xf8, 0x89, 0x39, 0x70, 0x0b, 0xca, 0x77, 0x3a, 0xc1, 0xac, 0xb0,
	0x99, 0x45, 0x7e, 0xda, 0xe0, 0xb5, 0xe9, 0x98, 0xf5, 0x15, 0x55, 0xec, 0x11, 0x59, 0x04, 0x6a,
	0x34, 0xe1, 0x77, 0xac, 0x48, 0x2d, 0x83, 0xd2, 0xee, 0x5a, 0xc3, 0x0b, 0x97, 0xb0, 0x5c, 0xfa,
	0x90, 0x2a, 0x16, 0xac, 0xed, 0xda, 0x0d, 0x37, 0xd4, 0x67, 0xdc, 0x04, 0x97, 0xcb, 0x53, 0x3a,
	0x0d, 0x1c, 0xdd, 0xce, 0xc2, 0xc0, 0x6d, 0xf0, 0xb8, 0xec, 0x2b, 0x3a, 0x51, 0x6c, 0x18, 0xb8,
	0xda, 0xb3, 0x00, 0x70, 0x07, 0x80, 0xcb, 0x73, 0x9e, 0x72, 0x79, 0xc3, 0x86, 0x41, 0x59, 0xbb,
	0x0d, 0x84, 0xfc, 0xb2, 0xa1, 0xd6, 0x13, 0x8a, 0x8f, 0x78, 0x44, 0x55, 0x5e, 0xdc, 0x3e, 0x38,
	0x6a, 0x9a, 0x31, 0x5d, 0xf3, 0x46, 0x6b, 0xdb, 0x6c, 0x85, 0xc9, 0x1b, 0x4c, 0x33, 0x16, 0x6a,
	0x26, 0x1e, 0x80, 0x77, 0x3d, 0x57, 0xad, 0x3b, 0x52, 0x6d, 0xfd, 0x6f, 0x86, 0xdd, 0xb7, 0x24,
	0x5c, 0xf0, 0x70, 0x13, 0x9c, 0x89, 0x48, 0x0a, 0x7d, 0x5e, 0xc7, 0x0a, 0xb5, 0x85, 0x2f, 0xa0,
	0x16, 0xf3, 0x24, 0x61, 0xc3, 0xa2, 0x0d, 0x5a, 0x68, 0xee, 0x5d, 0x42, 0x71, 0x0b, 0x5c, 0x9d,
	0x5e, 0xab, 0xcd, 0xdd, 0x85, 0x79, 0xec, 0x41, 0x65, 0xc8, 0x14, 0xe5, 0x89, 0x7c, 0x79, 0x06,
	0xfe, 0xc3, 0x6a, 0xd1, 0x03, 0xb7, 0x3f, 0x38, 0x0a, 0x07, 0xbe, 0x85, 0x00, 0xe5, 0xf3, 0x6e,
	0xaf, 0xdb, 0xef, 0xf8, 0x36, 0x56, 0xa1, 0xd2, 0x3b, 0xfb, 0x72, 0x75, 0x7a, 0xf4, 0xd5, 0x2f,
	0xe1, 0x7f, 0xe0, 0xe5, 0x46, 0xaf, 0xdb, 0xee, 0x0c, 0xfc, 0xb5, 0xd6, 0x0f, 0x07, 0x5c, 0x3d,
	0xdc, 0xf8, 0x1a, 0x9c, 0x7c, 0xec, 0xf0, 0x99, 0xa9, 0xcc, 0x18, 0xc4, 0xfa, 0xa6, 0xe9, 0x98,
	0xef, 0x00, 0xb1, 0xf0, 0x1d, 0x38, 0x17, 0x42, 0x31, 0x5c, 0xea, 0xe4, 0xc3, 0x11, 0x7c, 0x2c,
	0xfa, 0x03, 0x4f, 0x92, 0x27, 0x46, 0xf7, 0xf2, 0x8d, 0x64, 0x51, 0xdc, 0x1d, 0x15, 0x22, 0x1e,
	0xcf, 0xb2, 0x63, 0x7a, 0xff, 0xdc, 0x7c, 0x62, 0xe1, 0x5b, 0x58, 0x6f, 0x33, 0x55, 0x3c, 0xe0,
	0x8a, 0x25, 0xa9, 0xff, 0xfd, 0xe9, 0x89, 0x85, 0x87, 0x50, 0x39, 0x29, 0xf6, 0x7f, 0x65, 0x6c,
	0xb0, 0x5c, 0xc1, 0xe2, 0x2f, 0x21, 0x16, 0xbe, 0x02, 0xe7, 0xf3, 0x2d, 0x5f, 0x1d, 0xbb, 0xaa,
	0x07, 0x1d, 0xf0, 0xdb, 0x4c, 0x99, 0xc3, 0x20, 0xff, 0xed, 0x7e, 0x33, 0x84, 0x58, 0xfb, 0xf6,
	0x71, 0xfd, 0x32, 0x90, 0x82, 0x5e, 0x69, 0xca, 0xde, 0xf2, 0x27, 0xfb, 0xad, 0xac, 0xbf, 0xd6,
	0x83, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x1a, 0xe2, 0xb0, 0xc4, 0x7d, 0x05, 0x00, 0x00,
}
